# Cloud API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cloud
  namespace: latency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cloud
  template:
    metadata:
      labels:
        app: api-cloud
    spec:
      nodeSelector:
        topology.kubernetes.io/region: ap-southeast-1
        kubernetes.io/arch: arm64
      tolerations:
      - key: "arm64"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: api
        image: public.ecr.aws/v2f5y6u4/hybrid/latency-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: LOCATION
          value: "cloud"
        resources:
          requests:
            memory: "64Mi"
            cpu: 4
          limits:
            memory: "128Mi"
            cpu: 4
---
# Cloud API Service
apiVersion: v1
kind: Service
metadata:
  name: api-cloud-service
  namespace: latency-demo
spec:
  selector:
    app: api-cloud
  ports:
  - port: 8080
    targetPort: 8080
