# Pi API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pi
  namespace: latency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pi
  template:
    metadata:
      labels:
        app: api-pi
    spec:
      nodeSelector:
        eks.amazonaws.com/compute-type: hybrid
      containers:
      - name: api
        image: public.ecr.aws/v2f5y6u4/hybrid/latency-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: LOCATION
          value: "pi"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# Pi API Service
apiVersion: v1
kind: Service
metadata:
  name: api-pi-service
  namespace: latency-demo
spec:
  selector:
    app: api-pi
  ports:
  - port: 8080
    targetPort: 8080
