# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: hybrid-pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        topology.kubernetes.io/region: ap-southeast-1
        kubernetes.io/arch: arm64
      tolerations:
      - key: "arm64"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: hybrid-pipeline-demo
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
